{
 "title": "03 - Node.js Runtime",
 "refresh": "15s",
 "panels": [
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nodejs_event_loop_lag_seconds" }
   ]
  },
  {
   "title": "GC p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nodejs_gc_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Heap Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "CPU Time (process)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "process_cpu_user_seconds_total" }
   ]
  }
 ]
}