// TODO consider more than 4 categories at the launch
export const comps = {
	event: ['Image', 'TitleTexts', 'Content', 'Texts', 'BsEvent', 'RatingBs', 'TextArea', 'Entrance', 'Discussion', 'SortMenu'],
	home: ['Header', 'HeaderTexts', 'Quicks', 'CatFilter', 'Tools', 'Content'],
	setup: ['Personals', 'Cities', 'Indis', 'Basics', 'Favex', 'Picture', 'Groups'],
	editor: ['CatFilter', 'Filter', 'IntroTexts', 'Cropper', 'EventInfo'],
};

export const shareSrc = ['Facebook', 'Twitter', 'WhatsApp', 'Instagram', 'Email', 'Pozvat'];
import { FRIENDLY_MEETINGS, BENEFICIAL_EVENTS, CULTURAL_EVENTS, PROFESSIONAL_EVENTS } from '../shared/constants';

export const showObj = { quick: false, tools: 'basic', filter: false, times: false, sorts: false, sherlock: false, history: false, map: false, views: false, view: 'cityEvents' };
export const sherlockObj = { mode: 'standard', gender: null, minAge: 0, maxAge: 0, indis: [], groups: [], basics: [] };
export const emptyBrain = {
	user: {
		history: [],
		alerts: {},
		chats: [],
		comms: [],
		cardsView: { events: 1, users: 1 },
		galleryIDs: { invitesIn: {}, invitesOut: {} },
		chatsList: [],
		linkUsers: [],
		curCities: [],
		invitesIn: {},
		rateInProg: {},
		interInProg: {},
		privInProg: {},
		invitesOut: {},
		pastEve: {},
		eveInters: [],
		cities: [],
		eveUserIDs: {},
		prevLoadedContIDs: {},
		settings: { showAllThumbs: true },
		cols: { topEvents: 1, events: 2, users: 4, pastUsers: 5, eveStrips: 3, userStrips: 5, chatStrips: 1, inviteStrips: 3, locaStrips: 4, alertStrips: 4 },
		search: { events: {}, users: {}, chats: {}, links: {} },
		noMore: { chats: { chats: false, archive: false, inactive: false, hidden: false }, messInChats: [], search: {}, gallery: {}, alerts: false },
	},

	homeView: 'cityEvents',
	meetStats: {},
	citiesTypesInTimes: {},
	citiesContSync: {},
	events: {},
	bestOfIDs: [],
	users: {},
	cities: [],
	chatStoreInProg: {},
	rateInProg: {},
	interInProg: {},
	privInProg: {},
};

export const eventTitles = {
	a1: {
		// Outdoors / Venku
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', provětráme se městem a dáme ňákej ten urban exploration?',
			', vyrazíme na čerstvej vzduch někam na náměstí nebo do parku?',
			', dáme si ňákej ten venkovní chill a budem sledovat cvrkot ulic?',
			', nesedíme doma a jdem spolu objevovat architekturu našeho města?',
			', projdeme se historickým jádrem a probereme u toho všechno možný?',
			', vyrazíme na ňákej ten poctivej vejšlap po městskejch vyhlídkách?',
			', dáme pořádně dlouhou procházku a uvidíme, kam nás nohy zanesou?',
			', vyfoukáme si hlavy v uličkách a dáme si ňáco dobrýho po cestě?',
			', sejdeme se někde venku pod širým nebem a užijeme si atmošku?',
			', vyrazíme do ulic a zažijeme spolu tu pravou městskou atmosféru?',
		],
		instrumental: [
			'Provětráš se v ulicích města',
			'Vyrazíš na průzkum městskejch zákoutí',
			'Dáš si ňákej ten venkovní relax',
			'Půjdeš na čerstvej městskej vzduch',
			'Projdeš se historickým centrem',
			'Vyrazíš na vejšlap po památkách',
			'Dáš si pořádnou procházku městem',
			'Vyfoukáš si hlavu v městským ruchu',
			'Sejdeš se pod širým nebem',
			'Vyrazíš do víru velkoměsta',
		],
	},
	a2: {
		// Beer / Pivko
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', spláchneme prach dne orosenou plzničkou v ňáký dobrý hospě?',
			', probereme život u pár kousků skvěle ošetřenýho piva?',
			', skočíme na jedno rychlý orosený a ňákej ten hospodskej pokec?',
			', dáme ňákou tu vychlazenou dvanáctku a probereme všechny novinky?',
			', posedíme u dobrýho moku a budem jen tak spolu filozofovat?',
			', vyrazíme na pivní průzkum a zkusíme ňákej novej lokální pivovar?',
			', dáme ňákej ten poctivej krýgl a zakousneme k tomu něco dobrýho?',
			', zajdem na točený a vypustíme spolu páru z celýho tohohle tejdne?',
			', prolijeme hrdla zlatavým mokem v ňáký útulný starý pivnici?',
			', dáme si pár kousků a uvidíme, kam se ta naše debata dneska stočí?',
		],
		instrumental: [
			'Spláchneš prach orosenou plzničkou',
			'Probereš život u piva',
			'Skočíš na jedno rychlý orosený',
			'Dáš si ňákou tu dobrou dvanáctku',
			'Posedíš u zlatavýho moku',
			'Vyrazíš na průzkum lokálních pivovarů',
			'Dáš si pořádnej poctivej krýgl',
			'Zajdeš na skvěle ošetřený točený',
			'Proliješ hrdlo poctivým pivem',
			'Zajdeš na pár orosenejch kousků',
		],
	},
	a3: {
		// Coffee / Káva
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', nakopneme se ňákou tou výběrovou kávou v mý oblíbený kavárně?',
			', zajdem na kafe a pokecáme o všem, co nás zrovna teď napadne?',
			', probereme to v klidu u espressa nebo ňákýho jinýho kofeinu?',
			', skočíme na ňáký pořádně dobrý lattéčko se zajímavou kresbou?',
			', dáme si pracovní i nepracovní pauzu na kávu v centru města?',
			', posedíme v ňáký útulný kavárně a zapomeneme na okolní svět?',
			', dáme ňáký to cappuccino a probereme, jak se dneska vlastně máme?',
			', zajdem na kofeinovou vzpruhu a probereme ňáký ty naše plány?',
			', posedíme u šálku dobrý kávy a vychutnáme si tu chvilku klidu?',
			', dáme si ňákej ten odpolední dýchánek s vůní čerstvě mletý kávy?',
		],
		instrumental: [
			'Nakopneš se výběrovou kávou',
			'Zajdeš na kafe a dlouhej pokec',
			'Probereš věci u espressa',
			'Skočíš na pořádně dobrý lattéčko',
			'Dáš si pauzu na kofein',
			'Posedíš v útulný kavárně',
			'Dáš si cappuccino a klid',
			'Zajdeš na kofeinovou vzpruhu',
			'Posedíš u šálku dobrý kávy',
			'Užiješ si kávovej dýchánek',
		],
	},
	a4: {
		// Games / Hravé
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', zahrajem si něco a uvidíme, kdo z nás má většího herního ducha?',
			', dáme ňákou tu deskovku, u který se budeme moct trochu i pohádat?',
			', rozsekáme se v ňáký hře a vyzkoušíme naše strategický schopnosti?',
			', vyrazíme si zahrát něco akčního, co nás trochu zvedne ze židlí?',
			', dáme ňákej ten gaming a probereme u toho ty nejnovější herní pecky?',
			', protáhneme si mozkový závity u ňáký pořádně složitý logický hry?',
			', zapaříme něco spolu a uvidíme, jak nám to v týmu vlastně půjde?',
			', dáme herní večer plnej napětí, smíchu a možná i ňákejch těch emocí?',
			', vyzkoušíme ňákou úplně novou hru, kterou jsme ještě nikdy nehráli?',
			', rozjedeme ňákej ten herní turnaj a uvidíme, kdo z nás je fakt nejlepší?',
		],
		instrumental: [
			'Zahraješ si něco a zkusíš vyhrát',
			'Dáš si ňákou tu ostrou deskovku',
			'Rozsekáš se v strategický hře',
			'Vyrazíš si zahrát něco akčního',
			'Dáš si gaming a herní debatu',
			'Protáhneš mozkový závity u hry',
			'Zapaříš si něco v týmu',
			'Dáš si herní večer plnej smíchu',
			'Vyzkoušíš úplně novou hru',
			'Rozjedeš ňákej ten herní turnaj',
		],
	},
	a5: {
		// Indoors / Uvnitř
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', zalezeme někam do tepla, kde na nás nebude foukat ani pršet?',
			', dáme ňákej indoor pokec v klidu, kde nás nebude nikdo rušit?',
			', posedíme v teple u dobrýho pití a probereme všechno podstatný?',
			', schováme se před tím hnusným deštěm někam do fajn interiéru?',
			', dáme ňákou tu vnitřní akci a užijeme si tu útulnou atmosféru?',
			', posedíme někde v klidu, kde si budeme moct v pohodě popovídat?',
			', zajdem někam pod střechu a schováme se před tímhle počasím?',
			', dáme si totální pohodu uvnitř a nebudeme vůbec nic řešit?',
			', schováme se do interiéru a užijeme si ňákej ten komorní meetup?',
			', posedíme v ňákým útulnu, kde se budeme cítit jako doma?',
		],
		instrumental: [
			'Zalezeš do tepla před deštěm',
			'Dáš si v klidu indoor pokec',
			'Posedíš v teple u dobrýho pití',
			'Schováš se do fajn interiéru',
			'Dáš si ňákou tu vnitřní akci',
			'Posedíš v naprostým klidu',
			'Zajdeš pod střechu do útulna',
			'Dáš si pohodu v interiéru',
			'Schováš se dovnitř na pokec',
			'Posedíš v ňákým tom útulnu',
		],
	},
	a6: {
		// Party / Pařba
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', roztočíme to dneska večer a ukážeme všem, jak se umíme bavit?',
			', dáme ňákou tu kalbu a zapomeneme na všechny starosti všedních dnů?',
			', vyrazíme na pořádnou pařbu a budeme tancovat až do úplnýho rána?',
			', zakalíme spolu a uvidíme, co nám tahle noc všechno přinese?',
			', rozjedeme to dneska ve velkým stylu a užijeme si tu energii?',
			', dáme ňákou tu party, kde bude hrát skvělá hudba a bude fajn lidi?',
			', vyrazíme do víru noci a necháme se unášet tou party atmosférou?',
			', dáme si ňákou tu divočinu na baru a probereme život u drinku?',
			', provětráme parket v mým oblíbeným klubu a pořádně si to užijeme?',
			', zapaříme až do svítání a pak si dáme ňákou tu ranní snídani?',
		],
		instrumental: [
			'Roztočíš to dneska večer',
			'Dáš si ňákou tu pořádnou kalbu',
			'Vyrazíš na nezapomenutelnou pařbu',
			'Zakalíš si a uvidíš co přijde',
			'Rozjedeš to dneska ve velkým',
			'Dáš si party se skvělou hudbou',
			'Vyrazíš do nočního víru',
			'Dáš si divočinu na baru',
			'Provětráš se mnou parket',
			'Zapaříš si až do svítání',
		],
	},
	a7: {
		// Discussion / Diskuzní
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', probereme hluboký témata, který nás oba dva už delší dobu pálí?',
			', dáme ňákou tu intelektuální debatu o smyslu života a vesmíru?',
			', zafilozofujeme si o věcech, na který v běžným životě není čas?',
			', vyměníme si názory na aktuální dění a zkusíme se pochopit?',
			', probereme, co se děje ve světě a jak to vlastně všechno vnímáme?',
			', dáme konstruktivní diskuzi, která nás oba někam posune?',
			', posedíme a pokecáme vážně o tom, co je pro nás v životě důležitý?',
			', prodiskutujeme věci mezi nebem a zemí a uvidíme, kam dojdeme?',
			', dáme intelektuální dýchánek u čaje a budeme hledat pravdu?',
			', probereme život a uvidíme, jestli najdeme odpovědi na naše otázky?',
		],
		instrumental: [
			'Probereš hluboký témata',
			'Dáš si intelektuální debatu',
			'Zafilozofuješ si o životě',
			'Vyměníš si názory na svět',
			'Probereš aktuální dění',
			'Dáš si konstruktivní diskuzi',
			'Posedíš a pokecáš vážně',
			'Prodiskutuješ věci u čaje',
			'Dáš si intelektuální talk',
			'Probereš život a vesmír',
		],
	},
	a8: {
		// English / Anglicky
		beforeName: ['Hi, I am', 'Hello, it is', 'Zdravím, I am', 'Hey, I am', 'Ahoj, here is', 'Nazdar, I am', 'Čau, I am', 'Tady', 'Zdar, I am', 'Greetings, I am'],
		afterName: [
			', practice language together and overcome the fear of speaking?',
			', give English a try and see how much we actually remember?',
			', discuss interesting topics in English and expand our vocabulary?',
			', dáme ňákej ten English talk a nebudeme se bát dělat chyby?',
			', procvičíme si angličtinu v neformálním prostředí u kafe?',
			', zaspíkujeme si o všem možným a zlepšíme si tak plynulost?',
			', work on the improvement of our English speaking skills together?',
			', speak about everything in English and have some fun with it?',
			', give a chance to English and see where the conversation leads?',
			', talk in English together and maybe learn some new expressions?',
		],
		instrumental: [
			'Practice language and speaking',
			'Give English a real try',
			'Discuss topics in English',
			'Dáš si English talk v klidu',
			'Procvičíš si angličtinu',
			'Zaspíkuješ si o životě',
			'Improve your English skills',
			'Speak about everything',
			'Give English a fair chance',
			'Talk in English together',
		],
	},
	a9: {
		// Exercise / Cvičení
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', dáme si pořádně do těla a vyplavíme ňáký ty endorfiny?',
			', zaposilujeme si spolu a vzájemně se vyhecujeme k lepším výkonům?',
			', vyrazíme si zacvičit a uděláme tak něco dobrýho pro naše zdraví?',
			', zpotíme se v gymu nebo venku na hřišti a dáme si do těla?',
			', dáme ňákou tu makačku, po který se budeme cítit fakt skvěle?',
			', protáhneme se spolu a uvolníme tak veškerý to napětí z těla?',
			', vyrazíme na společnej trénink a probereme u toho ňáký cviky?',
			', dáme ňákej ten workout pod širým nebem a užijeme si pohyb?',
			', pohneme kostrou a uvidíme, co naše těla dneska vlastně zvládnou?',
			', uděláme něco pro naši fyzičku a budeme mít ze sebe radost?',
		],
		instrumental: [
			'Dáš si pořádně do těla',
			'Zaposiluješ si a zamakáš',
			'Vyrazíš si spolu zacvičit',
			'Zpotíš se při tréninku',
			'Dáš si ňákou tu makačku',
			'Protáhneš se a uvolníš',
			'Vyrazíš na společnej trénink',
			'Dáš si workout venku',
			'Pohneš se mnou kostrou',
			'Uděláš něco pro fyzičku',
		],
	},
	a10: {
		// Dogs / S pejsky
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', vyrazíme ven s našima chlupáčema a necháme je se proběhnout?',
			', vyvenčíme ty naše bestie spolu a probereme u toho psí život?',
			', dáme psí procházku někam, kde to mají naši hafani fakt rádi?',
			', pustíme ty naše hafoše k sobě a uvidíme, jestli si padnou do oka?',
			', vyrazíme na louku s pejskama a užijeme si společný odpoledne?',
			', dáme ňákej ten psí sraz a podělíme se o zkušenosti s výchovou?',
			', provětráme naše miláčky a necháme je se pořádně vyřádit?',
			', vyrazíme na psí hřiště a vyzkoušíme tam ňáký ty překážky?',
			', unavíme ty naše psí parťáky tak, aby doma pak jenom spokojeně spali?',
			', dáme společný venčení a probereme u toho všechno možný?',
		],
		instrumental: [
			'Vyrazíš ven s chlupáčem',
			'Vyvenčíš se mnou ty bestie',
			'Dáš si psí procházku',
			'Pustíš hafany k sobě',
			'Vyrazíš na louku s pejskem',
			'Dáš si ňákej ten psí sraz',
			'Provětráš se mnou miláčky',
			'Vyrazíš na psí hřiště',
			'Unavíš svýho hafoše',
			'Dáš si společný venčení',
		],
	},
	a11: {
		// Teens / Teens
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', dáme ňákej ten chill venku a nebudeme vůbec nic řešit?',
			', vyrazíme ven s celou touhle grupou a uvidíme, co se bude dít?',
			', uděláme akci pro mladý lidi, kde se budeme cítit fakt sami sebou?',
			', dáme ňákej ten meetup a probereme, co je teďka vlastně in?',
			', zevlíme spolu někde v parku a budeme jen tak pozorovat lidi?',
			', vyrazíme někam do streetu a užijeme si tu svobodu pohybu?',
			', dáme ňákou tu slezinu a poslechneme si u toho ňákou hudbu?',
			', posedíme někde venku na zídce a probereme naše plány?',
			', vyrazíme na ňákej hangout a poznáme ňáký nový lidi z okolí?',
			', dáme si ňákou tu naprostou pohodu a užijeme si dnešní den?',
		],
		instrumental: [
			'Dáš si ňákej ten chill venku',
			'Vyrazíš ven s celou grupou',
			'Uděláš akci pro mladý lidi',
			'Dáš si meetup a pokecáš',
			'Zevlíš se mnou někde v parku',
			'Vyrazíš do streetu za lidma',
			'Dáš si slezinu s hudbou',
			'Posedíš někde venku na zídce',
			'Vyrazíš na hangout v okolí',
			'Dáš si dneska totální pohodu',
		],
	},
	a12: {
		// Singles / Nezadaní
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', zkusíme se seznámit a uvidíme, jestli přeskočí ňáká ta jiskra?',
			', vyrazíme mezi další nezadaný lidi a zkusíme prolomit ledy?',
			', prolomíme tyhle trapný ledy a začneme se spolu normálně bavit?',
			', dáme rande na slepo a necháme se překvapit tím, kdo přijde?',
			', zkusíme najít spřízněnou duši, se kterou nám bude fakt fajn?',
			', dáme seznamovací akci, kde nebude nouze o zajímavý lidi?',
			', vyrazíme na ňákej speed dating a uvidíme, co se tam všechno stane?',
			', zkusíme ňáký to seznámení v klidu a bez zbytečnýho tlaku?',
			', dáme šanci osudu a uvidíme, jestli nám někoho přihraje do cesty?',
			', vyrazíme lovit do ulic a budeme se u toho hlavně dobře bavit?',
		],
		instrumental: [
			'Zkusíš se se mnou seznámit',
			'Vyrazíš mezi nezadaný lidi',
			'Prolomíš ty trapný ledy',
			'Dáš si rande na slepo',
			'Zkusíš najít spřízněnou duši',
			'Dáš si seznamovací akci',
			'Vyrazíš na speed dating',
			'Zkusíš seznámení v klidu',
			'Dáš dneska šanci osudu',
			'Vyrazíš lovit do ulic',
		],
	},
	a13: {
		// Business / Business
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', probereme byznys a podělíme se o naše pracovní zkušenosti?',
			', dáme networking a uvidíme, jestli si můžeme ňák vzájemně pomoct?',
			', vyměníme si nápady a probereme naše aktuální projekty?',
			', probereme možnou spolupráci a uvidíme, jestli to má smysl?',
			', dáme pracovní schůzku v ňákým zajímavým a inspirativním prostředí?',
			', probereme nový projekty, na kterejch zrovna teďka pracujeme?',
			', dáme ňákou tu obchodní řeč a uvidíme, kam se to všechno posune?',
			', vyrazíme na ňákej business lunch a probereme věci u jídla?',
			', probereme možný synergie mezi našima firmama nebo projekty?',
			', dáme ňákej ten brain-storming a zkusíme vymyslet něco novýho?',
		],
		instrumental: [
			'Probereš byznys a plány',
			'Dáš si networking a pokec',
			'Vyměníš si nápady a vize',
			'Probereš se mnou spolupráci',
			'Dáš si pracovní schůzku',
			'Probereš svý nový projekty',
			'Dáš si obchodní řeč',
			'Vyrazíš na business lunch',
			'Probereš se mnou synergie',
			'Dáš si brainstorming',
		],
	},
	a14: {
		// Nature / Příroda
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', vyrazíme do divočiny a odpočineme si od veškerýho civilního ruchu?',
			', dáme trek v lese a nadýcháme se čerstvýho jehličnatýho vzduchu?',
			', nadýcháme se v přírodě a načerpáme novou energii do příštích dnů?',
			', vyrazíme za město někam, kde je fakt božskej klid a ticho?',
			', dáme si vejlet do hor a užijeme si ty nádherný výhledy do okolí?',
			', odpočineme si od civilizace a budeme jen tak vnímat zvuky lesa?',
			', vyrazíme někam do zelena a budeme se jen tak toulat krajinou?',
			', dáme ňákou tu túru, u který se budeme moct pořádně zapotit?',
			', nadýcháme se lesního vzduchu a probereme u toho život?',
			', vyrazíme na ňákej ten vandr s batohem a užijeme si svobodu?',
		],
		instrumental: [
			'Vyrazíš do divočiny v klidu',
			'Dáš si trek v hlubokým lese',
			'Nadýcháš se v přírodě ticha',
			'Vyrazíš za město do ticha',
			'Dáš si vejlet do vysokejch hor',
			'Odpočineš si od lidí a ruchu',
			'Vyrazíš do zelena na túru',
			'Dáš si poctivou túru lesem',
			'Nadýcháš se čerstvýho vzduchu',
			'Vyrazíš na vandr s batohem',
		],
	},
	a15: {
		// Seniors / Senioři
		beforeName: ['Dobrý den, jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', posedíme a zavzpomínáme na to, jaký to bylo dřív za našich mladých let?',
			', dáme klidnou procházku parkem a probereme, co je u nás novýho?',
			', probereme co je novýho ve světě i v našich rodinách u šálku čaje?',
			', vyrazíme na akci pro starší lidi, kde se budeme cítit fakt dobře?',
			', posedíme u čaje a sušenek a probereme naše životní příběhy?',
			', dáme sraz zkušenějších lidí a podělíme se o naše moudra?',
			', probereme naše životní zkušenosti a zkusíme se vzájemně inspirovat?',
			', posedíme někde v klidu, kde si budeme moct v pohodě popovídat?',
			', dáme ňákou tu klidnou debatu o věcech, který jsou pro nás důležitý?',
			', sejdeme se jako za mlada a užijeme si společně strávenej čas?',
		],
		instrumental: [
			'Posedíš a zavzpomínáš na mládí',
			'Dáš si klidnou procházku parkem',
			'Probereš se mnou co je novýho',
			'Vyrazíš na akci pro starší',
			'Posedíš u čaje a sušenek',
			'Dáš si sraz zkušenějších',
			'Probereš životní zkušenosti',
			'Posedíš v naprostým klidu',
			'Dáš si klidnou debatu',
			'Sejdeš se se mnou jako dřív',
		],
	},
	a16: {
		// Gypsies / S Romy
		beforeName: ['Čau, já jsem', 'Ahoj, tady', 'Zdravím, já jsem', 'Nazdar, tady', 'Hele, jsem', 'Zdar, tady', 'Ahojte, jsem', 'Tady', 'Čau, já jsem', 'Zdravíčko, jsem'],
		afterName: [
			', dáme posezení s rodinou a probereme, co se u nás všechno děje?',
			', vyrazíme na romskou akci, kde bude skvělá hudba a tanec?',
			', zapaříme čardáše tak, jak to umíme jenom my, a užijeme si to?',
			', probereme věci v komunitě a uvidíme, co bychom mohli zlepšit?',
			', dáme romskej dýchánek s jídlem, pitím a hlavně dobrou náladou?',
			', sejdeme se a pokecáme o životě tak, jak to máme nejradši?',
			', dáme ňákou tu oslavu, na kterou budeme ještě dlouho vzpomínat?',
			', posedíme u nás doma nebo venku a probereme naše plány?',
			', dáme ňákou tu romskou zábavu plnou emocí a temperamentu?',
			', pokecáme o všem možným a uvidíme, kam nás ta debata zavede?',
		],
		instrumental: [
			'Dáš si posezení s rodinou',
			'Vyrazíš na romskou akci',
			'Zapaříš si čardáš s náma',
			'Probereš věci v komunitě',
			'Dáš si romskej dýchánek',
			'Sejdeš se a pokecáš s náma',
			'Dáš si pořádnou oslavu',
			'Posedíš u nás v rodině',
			'Dáš si romskou zábavu',
			'Pokecáš s náma o všem',
		],
	},
};

export const catsSrc = {
	cz: ['Přátelské', 'Kulturní', 'Odborné', 'Prospěšné'],
	en: ['Meetings', 'Events', 'Courses', 'Goodwill'],
};

export const ratingSrc = {
	event: {
		rating: ['nelíbí', 'dobrý', 'skvělý', 'výtečný!'],
		awards: {
			en: ['Wasteful', 'Superficial', 'Hello', 'Nazdar', 'Educational', 'Beneficial'],
			cz: ['konzumní', 'zbytečné', 'záživné', 'morální', 'naučné', 'Prospěšné'],
		},
		awardsTexts: [
			'Plýtvá, nadměrná spotřebá, konzum, luxus.',
			'Primitivní, nemorální, hloupé, povrchní.',
			'Zábavné, vizuální a nebo interaktivní',
			'Podporuje slušné chování a rozumné myšlení ',
			'Zvyšuje inteligenci, vzdělanost a přehled.',
			'Prospívá procesům, přírodě, zvířatům či lidem',
		],
	},
	meeting: {
		rating: ['slabé', 'dobrý', 'skvělý', 'výtečný!'],
		awards: {
			en: ['dislike', 'sympathetic', 'interesting', 'témata'],
			cz: ['nelíbí', 'sympaťáci', 'zajímavé', 'témata'],
		},
		awardsTexts: [
			'Konzumní či povrchní témata, nevhodné aktivity, nesmyslné, škodlivé či zbytečné prvky',
			'...sympatická, charismatická či inteligentně působící partička lidí, které chceš potkat',
			'Unikátní náplň nebo prospěšné, či obohacující aktivity či jiné nadstandartní prvky',
			'Zajímavá konverzační či expertní témata nebo atraktivní skladba osobnostních indikátorů',
		],
	},
	user: {
		rating: ['dobrý', 'skvělý'],
		awards: {
			en: ['Sympatie', 'Zajímavá', 'Prospěšná', 'Expertní'],
			cz: ['Sympathetic', 'Intriguing', 'Beneficial', 'Expertní'],
		},
		awardsTexts: ['Příjemný vzled, charisma, líbí se mi.', '...témata, zábavná nebo záživná.', '...témata, pro zdravou společnost.', '...témata, užitečná pro hodně lidí.'],
	},
	comment: {
		rating: ['slabé', 'dobré', 'skvělé', 'super'],
		awards: {
			en: ['Bezobsažné', 'Povrchní', 'Zajímavé', 'Inspirativní'],
			cz: ['Bezobsažné', 'Povrchní', 'Zajímavé', 'Inspirativní'],
		},
		awardsTexts: ['Bezobsažné, nezajímavé, neinspirativní.', 'Povrchní, nekvalitní, nekonzistentní.', 'Zajímavé, kvalitní, hodnotné.', 'Inspirativní, motivující, obohacující.'],
	},
};

const allEventTypes = [FRIENDLY_MEETINGS, CULTURAL_EVENTS, PROFESSIONAL_EVENTS, BENEFICIAL_EVENTS];
export const typesMap = new Map([...allEventTypes.flatMap(type => [...type])]);
export const catTypesStructure = catsSrc.cz.reduce(
	(map, value, i) =>
		map.set(value, {
			ids: Array.from(allEventTypes[i].keys()),
			names: Array.from(allEventTypes[i].values()),
		}),
	new Map()
);
